name: Build and Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master", "beta" ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn run lint
    - name: Build
      run: yarn run build

  Windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn run lint
    - name: Build
      run: yarn run build

  Mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn run lint
    - name: Build
      run: yarn run build
